
import { MatTableDataSource } from '@angular/material/table';

// The Contact Item structure.
export interface ContactItem {
    firstname: string;
    lastname: string;
    phone?: string;
}

// The Contacts. This could be moved to a local file for future expansion.
const CONTACT_DATA: ContactItem[] = [
    { firstname: 'Olaf', lastname: 'Lott' },
    { firstname: 'Molly', lastname: 'Vargas' },
    { firstname: 'Abul', lastname: 'Kendall' },
    { firstname: 'Raihan', lastname: 'Frey', phone: '56228 7805399' },
    { firstname: 'Flynn', lastname: 'Doherty', phone: '04040 7661663' },
    { firstname: 'Ibrar', lastname: 'Connelly', phone: '98870 5551093' },
    { firstname: 'Zhane', lastname: 'Turner' },
    { firstname: 'Khalid', lastname: 'Dickinson', phone: '97335 7383368' },
    { firstname: 'Sherri', lastname: 'Ayers', phone: '15554 4811955' },
    { firstname: 'Levison', lastname: 'Joseph' },
    { firstname: 'King', lastname: 'Tait' },
    { firstname: 'Calista', lastname: 'Pittman', phone: '08402 7689668' },
    { firstname: 'Skyla', lastname: 'Cunningham' },
    { firstname: 'Shanna', lastname: 'Cantrell' },
    { firstname: 'Sierra', lastname: 'Robbins' },
    { firstname: 'Aliyah', lastname: 'Parry', phone: '44175 3222523' },
    { firstname: 'Kaylan', lastname: 'Joyner' },
    { firstname: 'Shiloh', lastname: 'Ortega', phone: '67529 9892906' },
    { firstname: 'Suraj', lastname: 'Welsh', phone: '97122 0879851' },
    { firstname: 'Corben', lastname: 'Edmonds' },
    { firstname: 'Darci', lastname: 'Beech' },
    { firstname: 'Suranne', lastname: 'Swanson' },
    { firstname: 'Cameron', lastname: 'Mann' },
    { firstname: 'Raj', lastname: 'Griffith', phone: '40168 5366432' },
    { firstname: 'Kira', lastname: 'Reyna' },
    { firstname: 'Jaheim', lastname: 'Day' },
    { firstname: 'Antoinette', lastname: 'Bonilla', phone: '39714 7733735' },
    { firstname: 'Alaw', lastname: 'Wormald' },
    { firstname: 'Massimo', lastname: 'Correa', phone: '47267 9869767' },
    { firstname: 'Alayah', lastname: 'Knowles' },
    { firstname: 'Annabell', lastname: 'Montgomery' },
    { firstname: 'Jemma', lastname: 'Baird' },
    { firstname: 'Emil', lastname: 'Walter', phone: '19913 5878026' },
    { firstname: 'Finn', lastname: 'Chester' },
    { firstname: 'Daisy-May', lastname: 'Chase' },
    { firstname: 'Tyrone', lastname: 'Kent', phone: '86013 5429831' },
    { firstname: 'Herbert', lastname: 'Navarro' },
    { firstname: 'Israr', lastname: 'Ramsay' },
    { firstname: 'Elisa', lastname: 'Daugherty' },
    { firstname: 'Raul', lastname: 'Mora' },
    { firstname: 'Mariyam', lastname: 'Trevino', phone: '64914 4990739' },
    { firstname: 'Abubakr', lastname: 'Milne' },
    { firstname: 'Nieve', lastname: 'Brady', phone: '33950 2315974' },
    { firstname: 'Daniyal', lastname: 'Mcdowell' },
    { firstname: 'Cadi', lastname: 'Rose' },
    { firstname: 'Darius', lastname: 'Choi' },
    { firstname: 'Joann', lastname: 'Villegas' },
    { firstname: 'Julie', lastname: 'Calvert', phone: '85403 4372384' },
    { firstname: 'Trent', lastname: 'Garrett', phone: '92191 5563075' },
    { firstname: 'Pauline', lastname: 'Philip' },
    { firstname: 'Trystan', lastname: 'Sexton' },
    { firstname: 'Cain', lastname: 'Benjamin' },
    { firstname: 'Johan', lastname: 'Kline', phone: '13879 9986065' },
    { firstname: 'Clarissa', lastname: 'Daniels', phone: '09981 5693100' },
    { firstname: 'Wilbur', lastname: 'Davenport' },
    { firstname: 'Evie-May', lastname: 'Palmer' },
    { firstname: 'Sade', lastname: 'Schaefer', phone: '04009 8691835' },
    { firstname: 'Marek', lastname: 'Gonzales' },
    { firstname: 'Blane', lastname: 'Briggs' },
    { firstname: 'Farrell', lastname: 'Ortiz' },
    { firstname: 'Magnus', lastname: 'Jones' },
    { firstname: 'Parker', lastname: "O'Neill" },
    { firstname: 'Gary', lastname: 'Gallagher' },
    { firstname: 'Marion', lastname: 'Butler' },
    { firstname: 'Tymoteusz', lastname: 'Rodgers', phone: '53277 5926980' },
    { firstname: 'Owais', lastname: 'Medina', phone: '54719 6444890' },
    { firstname: 'Gabriela', lastname: 'Booker' },
    { firstname: 'Zion', lastname: 'Mckee' },
    { firstname: 'Rianne', lastname: 'Leblanc' },
    { firstname: 'Keiron', lastname: 'Coates' },
    { firstname: 'Isra', lastname: 'Page' },
    { firstname: 'Inez', lastname: 'Mejia', phone: '03982 6890705' },
    { firstname: 'Anastazja', lastname: 'Mccartney', phone: '96075 7728096' },
    { firstname: 'Ronaldo', lastname: 'Squires' },
    { firstname: 'Roan', lastname: 'Mathis', phone: '62422 2427240' },
    { firstname: 'Zayne', lastname: 'Rosa', phone: '98949 6454748' },
    { firstname: 'Sonny', lastname: 'Hibbert' },
    { firstname: 'Abbi', lastname: 'Blackwell' },
    { firstname: 'Elen', lastname: 'Webber' },
    { firstname: 'Melvin', lastname: 'Lloyd', phone: '58935 2153077' },
    { firstname: 'Katie', lastname: 'Atherton' },
    { firstname: 'Ann', lastname: 'Emerson', phone: '06949 4731310' },
    { firstname: 'Armaan', lastname: 'Oliver' },
    { firstname: 'Henley', lastname: 'Odom' },
    { firstname: 'Abbigail', lastname: 'Salinas' },
    { firstname: 'Simrah', lastname: 'Ibarra', phone: '02805 3596173' },
    { firstname: 'Anaya', lastname: 'Long' },
    { firstname: 'Eleanor', lastname: 'Esquivel', phone: '20591 5196019' },
    { firstname: 'Manha', lastname: 'Preece' },
    { firstname: 'Gwion', lastname: 'Carey' },
    { firstname: 'Chester', lastname: 'Massey' },
    { firstname: 'Mia', lastname: 'Rush' },
    { firstname: 'Neive', lastname: 'Rivera' },
    { firstname: 'Danniella', lastname: 'Terrell' },
    { firstname: 'Riaz', lastname: 'Howarth', phone: '85993 3886940' },
    { firstname: 'Zaid', lastname: 'Corbett' },
    { firstname: 'Johnnie', lastname: 'Gill', phone: '65097 9681042' },
    { firstname: 'Luke', lastname: 'Greig' },
    { firstname: 'Akaash', lastname: 'Flowers' },
    { firstname: 'Nellie', lastname: 'Roberson', phone: '37850 1826417' },
    { firstname: 'Jayce', lastname: 'Padilla' },
    { firstname: 'Christopher', lastname: 'Burt', phone: '20376 9487380' },
    { firstname: 'Carlie', lastname: 'Wilder' },
    { firstname: 'Hubert', lastname: 'Doherty' },
    { firstname: 'Aqib', lastname: 'Foreman' },
    { firstname: 'Georgia', lastname: 'Mccabe' },
    { firstname: 'Asmaa', lastname: 'Reese' },
    { firstname: 'Ihsan', lastname: 'Hancock', phone: '73635 6019339' },
    { firstname: 'Anish', lastname: 'Robson' },
    { firstname: 'Umair', lastname: 'Alfaro' },
    { firstname: 'Poppie', lastname: 'Delarosa', phone: '39045 3404474' },
    { firstname: 'Yunus', lastname: 'Kinney' },
    { firstname: 'Ivan', lastname: 'Halliday' },
    { firstname: 'Gregory', lastname: 'Conner' },
    { firstname: 'Hanna', lastname: 'Peel', phone: '40828 1090530' },
    { firstname: 'Hadiqa', lastname: 'Miranda' },
    { firstname: 'Miya', lastname: 'French' },
    { firstname: 'Louisa', lastname: 'Metcalfe', phone: '77136 1189010' },
    { firstname: 'Nigel', lastname: 'Edwards' },
    { firstname: 'Naseem', lastname: 'Wade' },
    { firstname: 'Bernard', lastname: 'Neale', phone: '88530 7988153' },
    { firstname: 'Kitty', lastname: 'Trejo' },
    { firstname: 'Anais', lastname: 'Woodard', phone: '17262 9100128' },
    { firstname: 'Dannielle', lastname: 'Kelly' },
    { firstname: 'Angus', lastname: 'Winters' },
    { firstname: 'Adnan', lastname: 'Gibbs' },
    { firstname: 'Tyriq', lastname: 'Valencia', phone: '89154 8536483' },
    { firstname: 'Daryl', lastname: 'Milne' },
    { firstname: 'Kimberly', lastname: 'Gutierrez' },
    { firstname: 'Asiya', lastname: 'Rodgers' },
    { firstname: 'Mabel', lastname: 'Fields', phone: '62425 8090772' },
    { firstname: 'Mariyah', lastname: 'Ramsay' },
    { firstname: 'Jolyon', lastname: 'Redmond', phone: '63546 5647338' },
    { firstname: 'Kynan', lastname: 'Hicks' },
    { firstname: 'Merryn', lastname: 'Rosales' },
    { firstname: 'Ted', lastname: 'Lester' },
    { firstname: 'Sukhmani', lastname: 'Goodwin' },
    { firstname: 'Burhan', lastname: 'Gonzalez' },
    { firstname: 'Helena', lastname: 'Bowes' },
    { firstname: 'Elisha', lastname: 'Armitage' },
    { firstname: 'Marisa', lastname: 'Rocha' },
    { firstname: 'Missy', lastname: 'Mcgee', phone: '38984 7983945' },
    { firstname: 'Antonia', lastname: 'Shaw' },
    { firstname: 'Mike', lastname: 'Moyer' },
    { firstname: 'Loki', lastname: 'Fritz' },
    { firstname: 'Jose', lastname: 'Atkins' },
    { firstname: 'Jaskaran', lastname: 'Hayward', phone: '44288 6980064' },
    { firstname: 'Constance', lastname: 'Weston', phone: '61045 3346599' },
    { firstname: 'Bruce', lastname: 'Case' },
    { firstname: 'Lili', lastname: 'Mckee', phone: '42462 3734046' },
    { firstname: 'Adrianna', lastname: 'Ware' },
    { firstname: 'Reece', lastname: 'Underwood' },
    { firstname: 'Zunairah', lastname: 'Clemons', phone: '88944 3253998' },
    { firstname: 'Lena', lastname: 'Holt' },
    { firstname: 'Tim', lastname: 'Mann', phone: '35629 9786831' },
    { firstname: 'Yash', lastname: 'Thorpe', phone: '69276 7957478' },
    { firstname: 'Akram', lastname: 'Corona', phone: '17314 4856830' },
    { firstname: 'Sioned', lastname: 'Humphreys', phone: '62186 7744284' },
    { firstname: 'Tamsin', lastname: 'Kumar', phone: '14081 1940597' },
    { firstname: 'Roseanna', lastname: 'Esparza', phone: '23083 6815689' },
    { firstname: 'Kaiya', lastname: 'Burn', phone: '92008 5752405' },
    { firstname: 'Sameeha', lastname: 'Daniels' },
    { firstname: 'Saffa', lastname: 'Pope' },
    { firstname: 'Stefanie', lastname: 'Griffith' },
    { firstname: 'Iylah', lastname: 'Hume' },
    { firstname: 'Layla-Mae', lastname: 'Edge' },
    { firstname: 'Kiri', lastname: 'Orozco', phone: '59505 4070300' },
    { firstname: 'Allison', lastname: 'Beard' },
    { firstname: 'Aayat', lastname: 'Mack' },
    { firstname: 'Marina', lastname: 'Sutton', phone: '48397 0434106' },
    { firstname: 'Zephaniah', lastname: 'Leonard', phone: '37511 5690396' },
    { firstname: 'Nylah', lastname: 'Howells', phone: '67133 2185818' },
    { firstname: 'Tatiana', lastname: 'Britton' },
    { firstname: 'Ciaran', lastname: 'Orr' },
    { firstname: 'Mikael', lastname: 'Lamb' },
    { firstname: 'Rick', lastname: 'Ross' },
    { firstname: 'Reggie', lastname: 'Harrington' },
    { firstname: 'Eloise', lastname: 'Nicholson' },
    { firstname: 'Reem', lastname: 'Philip' },
    { firstname: 'Abbi', lastname: 'Mcgill' },
    { firstname: 'Kean', lastname: 'Pace' },
    { firstname: 'Olli', lastname: 'Garner' },
    { firstname: 'Nathalie', lastname: 'Parrish', phone: '71979 5661222' },
    { firstname: 'Imogen', lastname: 'Allen' },
    { firstname: 'Sofija', lastname: 'Love' },
    { firstname: 'Amie', lastname: 'Fitzgerald', phone: '11726 9987235' },
    { firstname: 'Neriah', lastname: 'Fraser' },
    { firstname: 'Stanley', lastname: 'Cox' },
    { firstname: 'Jaden', lastname: 'Anthony' },
    { firstname: 'Vlad', lastname: 'Hills' },
    { firstname: 'Miley', lastname: 'Blackburn' },
    { firstname: 'Alfie', lastname: 'Kennedy', phone: '05431 8246297' },
    { firstname: 'Lleyton', lastname: 'Gomez' },
    { firstname: 'Teri', lastname: 'Goodman' },
    { firstname: 'Edith', lastname: 'Schwartz' },
    { firstname: 'Mara', lastname: 'Salgado' },
    { firstname: 'Molly', lastname: 'Squires' },
    { firstname: 'Grady', lastname: 'Holcomb', phone: '92242 3445572' },
    { firstname: 'Arham', lastname: 'Gilmour' },
    { firstname: 'Nazim', lastname: 'Forbes' },
    { firstname: 'Ashley', lastname: 'Prince', phone: '94825 0193727' },
    { firstname: 'Yassin', lastname: 'Landry' },
    { firstname: 'Charli', lastname: 'Coffey' },
    { firstname: 'Benn', lastname: 'Santos', phone: '26662 3622544' },
    { firstname: 'Hughie', lastname: 'Underwood', phone: '85855 5000598' },
    { firstname: 'Anderson', lastname: 'Almond' },
    { firstname: 'Kaelan', lastname: 'Moody' },
    { firstname: 'Kajal', lastname: 'Colon' },
    { firstname: 'Sanaya', lastname: 'Hogan' },
    { firstname: 'Muna', lastname: 'Torres' },
    { firstname: 'Everly', lastname: 'Gates' },
    { firstname: 'Samual', lastname: 'Whitworth' },
    { firstname: 'Kiran', lastname: 'Amin', phone: '51769 4176292' },
    { firstname: 'Ishaq', lastname: 'Ford' },
    { firstname: 'Toby', lastname: 'Fellows' },
    { firstname: 'Misbah', lastname: 'Langley' },
    { firstname: 'River', lastname: 'Lucero' },
    { firstname: 'Whitney', lastname: 'Salas' },
    { firstname: 'Tyreke', lastname: 'Walter', phone: '85705 5359126' },
    { firstname: 'Donte', lastname: 'Mason', phone: '90098 2966656' },
    { firstname: 'Kaya', lastname: 'Boyle' },
    { firstname: 'Yasir', lastname: 'Pickett', phone: '65682 5167675' },
    { firstname: 'Chanel', lastname: 'Lamb' },
    { firstname: 'Nancy', lastname: 'Mcpherson' },
    { firstname: 'Siyana', lastname: 'Robbins' },
    { firstname: 'Natalia', lastname: 'Rudd', phone: '69755 2029528' },
    { firstname: 'Willa', lastname: 'Robins', phone: '78547 7330432' },
    { firstname: 'Rhianne', lastname: 'Enriquez' },
    { firstname: 'Blade', lastname: 'Ortega', phone: '08876 2947057' },
    { firstname: 'Kaja', lastname: 'Hess', phone: '53193 7049688' },
    { firstname: 'Marsha', lastname: 'Padilla' },
    { firstname: 'Cataleya', lastname: 'Lancaster', phone: '36526 6592737' },
    { firstname: 'Bronwyn', lastname: 'Reilly', phone: '95243 3811678' },
    { firstname: 'Sandra', lastname: 'Hough' },
    { firstname: 'Raife', lastname: 'Person' },
    { firstname: 'Samirah', lastname: 'Weeks' },
    { firstname: 'Anis', lastname: 'Rahman' },
    { firstname: 'Konrad', lastname: 'Plant' },
    { firstname: 'Bevan', lastname: 'Squires' },
    { firstname: 'Ciaron', lastname: 'Logan' },
    { firstname: 'Elara', lastname: 'Hills' },
    { firstname: 'Sanna', lastname: 'Mair', phone: '80792 4018533' },
    { firstname: 'Zayne', lastname: 'Byers' },
    { firstname: 'Natasha', lastname: 'Patel' },
    { firstname: 'Danyaal', lastname: 'Fischer' },
    { firstname: 'Ayub', lastname: 'Esparza' },
    { firstname: 'Janae', lastname: 'Mullins', phone: '19707 2425983' },
    { firstname: 'Layla', lastname: 'Braun' },
    { firstname: 'Tarun', lastname: 'Haines', phone: '32722 4388509' },
    { firstname: 'Carson', lastname: 'Philip', phone: '43834 4961196' },
    { firstname: 'Ray', lastname: 'Rangel', phone: '37109 4296222' },
    { firstname: 'Kaylem', lastname: 'Bush' },
    { firstname: 'Ayesha', lastname: 'Noel' },
    { firstname: 'Stefania', lastname: 'Tierney' },
    { firstname: 'Jayda', lastname: 'Love' },
    { firstname: 'Ana', lastname: 'Lees', phone: '91720 6439984' },
    { firstname: 'Archie', lastname: 'Davila', phone: '48240 0811400' },
    { firstname: 'Kasim', lastname: 'Holding' },
    { firstname: 'Rubi', lastname: 'Vang', phone: '35899 3761068' },
    { firstname: 'Alyx', lastname: 'Dunkley', phone: '28441 0909452' },
    { firstname: 'Ronaldo', lastname: 'Bryan', phone: '52329 7153744' },
    { firstname: 'Georgie', lastname: 'Avery' },
    { firstname: 'Mathilda', lastname: 'Mckinney' },
    { firstname: 'Keiren', lastname: 'Cortes' },
    { firstname: 'Tayler', lastname: 'Schwartz' },
    { firstname: 'Bonnie', lastname: 'Healy' },
    { firstname: 'Aliza', lastname: 'Kouma' },
    { firstname: 'Manal', lastname: 'Hernandez' },
    { firstname: 'Abbey', lastname: 'Castro' },
    { firstname: 'Zoe', lastname: 'Puckett' },
    { firstname: 'Flynn', lastname: 'Hackett', phone: '06400 3428100' },
    { firstname: 'Reo', lastname: 'Ellwood', phone: '61837 3190556' },
    { firstname: 'Stacie', lastname: 'Brooks' },
    { firstname: 'Zakary', lastname: 'Dowling' },
    { firstname: 'Tania', lastname: 'Worthington' },
    { firstname: 'Zahid', lastname: 'Richards' },
    { firstname: 'Constance', lastname: 'Henson' },
    { firstname: 'Robbie', lastname: 'Sloan' },
    { firstname: 'Raheem', lastname: 'Taylor' },
    { firstname: 'Veronica', lastname: 'Carpenter' },
    { firstname: 'Ruby-Rose', lastname: 'Knox' },
    { firstname: 'Abi', lastname: 'Truong', phone: '68875 8557914' },
    { firstname: 'Briana', lastname: 'Pham', phone: '56649 5868525' },
    { firstname: 'Zeeshan', lastname: 'Mccormick' },
    { firstname: 'Ingrid', lastname: 'Edge' },
    { firstname: 'Primrose', lastname: 'Felix' },
    { firstname: 'Clementine', lastname: 'Barlow' },
    { firstname: 'Pedro', lastname: 'Prentice' },
    { firstname: 'Kit', lastname: 'Khan' },
    { firstname: 'Charles', lastname: 'Faulkner' },
    { firstname: 'Faye', lastname: 'Fenton', phone: '58240 8437517' },
    { firstname: 'Louisa', lastname: 'George' },
    { firstname: 'Belle', lastname: 'Cleveland', phone: '15296 1511375' },
    { firstname: 'Terence', lastname: 'Murphy', phone: '57424 6684324' },
    { firstname: 'Mared', lastname: 'Abbott', phone: '80585 3822122' },
    { firstname: 'Saniya', lastname: 'Robson' },
    { firstname: 'Hakim', lastname: 'Roth' },
    { firstname: 'Adil', lastname: 'Warner' },
    { firstname: 'Jaspal', lastname: 'Stevens' },
    { firstname: 'Ihsan', lastname: 'Wills' },
    { firstname: 'Rafi', lastname: 'Ford' },
    { firstname: 'Mattie', lastname: 'Sheehan', phone: '61620 4577935' },
    { firstname: 'Haiden', lastname: 'Horton' },
    { firstname: 'Shantelle', lastname: 'Cox' },
    { firstname: 'Leon', lastname: 'Odonnell' },
    { firstname: 'Ashton', lastname: 'Penn', phone: '46940 1507281' },
    { firstname: 'Vikram', lastname: 'Wyatt' },
    { firstname: 'Francesca', lastname: 'Hunter' },
    { firstname: 'Zahara', lastname: 'Pace', phone: '14012 4947484' },
    { firstname: 'Kajetan', lastname: 'Salgado' },
    { firstname: 'Mea', lastname: 'Wall', phone: '42612 7043625' },
    { firstname: 'Iman', lastname: 'Guy' },
    { firstname: 'Katrina', lastname: 'Mcbride' },
    { firstname: 'Celyn', lastname: 'Whittaker' },
    { firstname: 'Alexandria', lastname: 'Simpson', phone: '74802 3939517' },
    { firstname: 'Kate', lastname: 'Morin', phone: '62947 0984154' },
    { firstname: 'Felicity', lastname: 'Beltran', phone: '13779 0417685' },
    { firstname: 'Sami', lastname: 'Jeffery', phone: '99676 3808276' },
    { firstname: 'Waqar', lastname: 'Silva' },
    { firstname: 'Shahzaib', lastname: 'Frost' },
    { firstname: 'Pola', lastname: 'Hansen', phone: '13931 0697949' },
    { firstname: 'Huda', lastname: 'Laing' },
    { firstname: 'Teddy', lastname: 'Head' },
    { firstname: 'Orlaith', lastname: 'Powers', phone: '53738 2541733' },
    { firstname: 'Dilara', lastname: 'Bouvet' },
    { firstname: 'Laylah', lastname: 'Callahan' },
    { firstname: 'Campbell', lastname: 'Dunne', phone: '16872 8184060' },
    { firstname: 'Kajus', lastname: 'Hulme' },
    { firstname: 'Ava-Grace', lastname: 'Knights' },
    { firstname: 'Eesha', lastname: 'Simon' },
    { firstname: 'Charlene', lastname: 'Lyons' },
    { firstname: 'Pauline', lastname: 'Read' },
    { firstname: 'Archie', lastname: 'Dunn' },
    { firstname: 'Gregg', lastname: 'Potter', phone: '36066 3553172' },
    { firstname: 'Zakariyya', lastname: 'Hughes', phone: '81252 4423584' },
    { firstname: 'Eshaal', lastname: 'Giles' },
    { firstname: 'Carlos', lastname: 'Mckee' },
    { firstname: 'Susanna', lastname: 'Figueroa', phone: '79931 7636846' },
    { firstname: 'Dalton', lastname: 'Singleton' },
    { firstname: 'Harun', lastname: 'Knox' },
    { firstname: 'Tadhg', lastname: 'Benton' },
    { firstname: 'Zaid', lastname: 'Alcock' },
    { firstname: 'Courtney', lastname: 'Goodwin' },
    { firstname: 'Brodie', lastname: 'Wu', phone: '91854 9895983' },
    { firstname: 'Zayaan', lastname: 'Baxter' },
    { firstname: 'Melvin', lastname: 'Schroeder' },
    { firstname: 'Mallory', lastname: 'Dawson', phone: '75913 5244054' },
    { firstname: 'Marlene', lastname: 'Collier' },
    { firstname: 'Kanye', lastname: 'Gunn' },
    { firstname: 'Patrick', lastname: 'Mccullough' },
    { firstname: 'Wayne', lastname: 'Mcphee' },
    { firstname: 'Peyton', lastname: 'Nguyen' },
    { firstname: 'Breanna', lastname: 'Nelson' },
    { firstname: 'Daniele', lastname: 'Decker', phone: '50186 1702029' },
    { firstname: 'Ember', lastname: 'Holding' },
    { firstname: 'Abdurahman', lastname: 'Lin' },
    { firstname: 'Yara', lastname: 'Swanson' },
    { firstname: 'Velma', lastname: 'Foreman', phone: '80762 5082614' },
    { firstname: 'John-James', lastname: 'Fraser' },
    { firstname: 'Juan', lastname: 'Mccaffrey' },
    { firstname: 'Kerys', lastname: 'Nolan', phone: '65494 1263377' },
    { firstname: 'Sanah', lastname: 'Black' },
    { firstname: 'Samantha', lastname: 'Joseph', phone: '08032 8185100' },
    { firstname: 'Tasnia', lastname: 'Cooley', phone: '72715 8138110' },
    { firstname: 'Hawa', lastname: 'Alfaro' },
    { firstname: 'Kaydee', lastname: 'Williamson', phone: '87948 6094490' },
    { firstname: 'Jagoda', lastname: 'Hooper' },
    { firstname: 'Ainsley', lastname: 'Cote' },
    { firstname: 'Candice', lastname: 'Andrews' },
    { firstname: 'Mali', lastname: 'Meyer' },
    { firstname: 'Jannah', lastname: 'Hendrix', phone: '96823 0022167' },
    { firstname: 'Ivy-Rose', lastname: 'Reyes' },
    { firstname: 'Mert', lastname: 'Calhoun' },
    { firstname: 'Malcolm', lastname: 'Findlay' },
    { firstname: 'Hailie', lastname: 'Barr' },
    { firstname: 'Daniaal', lastname: 'Mcdaniel', phone: '34236 1035695' },
    { firstname: 'Mylee', lastname: 'Atherton' },
    { firstname: 'Shayna', lastname: 'Hoffman' },
    { firstname: 'Thelma', lastname: 'Chaney' },
    { firstname: 'Farrah', lastname: 'Ratcliffe', phone: '03997 6989796' },
    { firstname: 'Shahid', lastname: 'Garrison', phone: '75297 5797906' },
    { firstname: 'Emmanuel', lastname: 'Howell', phone: '25730 5062808' },
    { firstname: 'Rami', lastname: 'Clay' },
    { firstname: 'Claude', lastname: 'Croft', phone: '67912 9471030' },
    { firstname: 'Addie', lastname: 'Proctor' },
    { firstname: 'Rhiana', lastname: 'Mitchell' },
    { firstname: 'May', lastname: 'Duggan' },
    { firstname: 'Eliza', lastname: 'Knott' },
    { firstname: 'Faris', lastname: 'Jennings', phone: '17916 2247844' },
    { firstname: 'Emanuel', lastname: 'Chan' },
    { firstname: 'Sophie-Louise', lastname: 'Gates', phone: '05034 0774601' },
    { firstname: 'Kianna', lastname: 'Wagstaff' },
    { firstname: 'Jared', lastname: 'Wagner' },
    { firstname: 'Carrie-Ann', lastname: 'Mcgregor' },
    { firstname: 'Shania', lastname: 'Buckley' },
    { firstname: 'Sol', lastname: 'Mullen' },
    { firstname: 'Kason', lastname: 'Chang', phone: '26033 8043859' },
    { firstname: 'Adelle', lastname: 'David' },
    { firstname: 'Griffin', lastname: 'Woodcock', phone: '43431 9212812' },
    { firstname: 'Emerson', lastname: 'Davies' },
];

/**
 * Data source for the Contact view. This class should
 * encapsulate all logic for fetching and manipulating the displayed data
 * (including sorting, pagination, and filtering).
 */
export class ContactDataSource extends MatTableDataSource<ContactItem> {
    constructor() {
        super(Object.assign(CONTACT_DATA));
    }

    /**
     * Paginate the data (client-side). If you're using server-side pagination,
     * this would be replaced by requesting the appropriate data from the server.
     */
    private getPagedData(data: ContactItem[]): ContactItem[] {
        if (this.paginator) {
            const startIndex = this.paginator.pageIndex * this.paginator.pageSize;
            return data.splice(startIndex, this.paginator.pageSize);
        } else {
            return data;
        }
    }

    /**
     * Sort the data (client-side). If you're using server-side sorting,
     * this would be replaced by requesting the appropriate data from the server.
     */
    private getSortedData(data: ContactItem[]): ContactItem[] {
        if (!this.sort || !this.sort.active || this.sort.direction === '') {
            return data;
        }

        return data.sort((a, b) => {
            const isAsc = this.sort?.direction === 'asc';
            switch (this.sort?.active) {
                case 'firstname': return compare(a.firstname, b.firstname, isAsc);
                case 'lastname': return compare(a.lastname, b.lastname, isAsc);
                case 'phone': return compare(+a.phone, +b.phone, isAsc);
                default: return 0;
            }
        });
    }
    public deleteContact(contact) {
        var found = -1;
        for (var i = 0; i < this.data.length; i++) {
            if (this.data[i] == contact) {
                found = i;
                break;
            }
        }
        if (found > -1) {
            this.data.splice(found, 1);
            this._updateChangeSubscription();
        }
    }
    public addContact(contact) {
        this.data.push(contact);
        this._updateChangeSubscription();
    }
    applyFilter(filterValue: string) {
        filterValue = filterValue.trim(); // Remove whitespace
        filterValue = filterValue.toLowerCase(); // MatTableDataSource defaults to lowercase matches
        this.filter = filterValue;
    }

}

/** Simple sort comparator for example ID/Name columns (for client-side sorting). */
function compare(a: string | number, b: string | number, isAsc: boolean): number {
    return (a < b ? -1 : 1) * (isAsc ? 1 : -1);
}
